refactor(test): replaced Dependencies annotation #5087
Terasology/Health pull request #106
Opened 2023-11-24 14:10 UTC by Sabo2k

change BlockTest, DamageEventTest, RestorationTest, RegenTest

2023-11-24 19:11 UTC, jdrueckert requested changes

2023-11-24 19:11 UTC, jdrueckert commented on src/test/java/org/terasology/module/health/BlockTest.java
>  @Tag("MteTest")
As mentioned in https://github.com/MovingBlocks/Terasology/issues/5087
> the class annotation `@IntegrationEnvironment` [...] will apply `MTEExtension`, mark it with an `MteTest` JUnit tag

Accordingly, you can remove the `@ExtendWith` and `@Tag` annotations as well.

Same for all other changes

2023-11-27 19:28 UTC, skaldarnar commented
@Sabo2k please have a look at the reported CheckStyle warnings in this PR (unused imports and the code style when using annotations). Once those are resolved, we can merge this 👍

2023-11-30 13:32 UTC, Sabo2k commented
When I cloned my forked Health-repo, I couldn't run all tests and static code checks for this module using 
```
gradlew :module:Health:check
``` 

because it didn't contain a ```build.gradle``` file. 

Do you guys think it would be a good idea to add one to the repository? 🙂

2023-12-05 17:07 UTC, jdrueckert commented
> because it didn't contain a `build.gradle` file.

This is expected based on how our CI jobs are set up.
You can run checks locally for specific modules from your workspace root using `./gradlew :modules:Health:check`

2023-12-05 17:09 UTC, jdrueckert approved these changes
Looks good to me :+1:

2023-12-05 17:10 UTC, merged