Height extras
Terasology/Health pull request #36
Opened 2020-03-03 14:04 UTC by godfather2

## Contains
An attempt to fix a sub issue of https://github.com/MovingBlocks/Terasology/issues/2535 along with https://github.com/MovingBlocks/Terasology/pull/3841
The vertical damage speed threshold varies with the player's height. I noticed that at  heights greater than 30,the player took damage on horizontal collision.Hence, i made the character immune to horizontal damage at those heights.

- [x] Increase/Decrease damage from fall. (30m giant should not die of a 15m fall). Define function/proportionality constant same as above.
## How to test

Change the player's height and you will see that the it won't lose any health on jumping.

2020-03-04 15:18 UTC, e-aakash reviewed
Haven't tested yet, but these are some things that I noticed. 
Maybe values can be extracted away to HealthComponent (making it customizable).

2020-03-04 15:18 UTC, e-aakash commented on src/main/java/org/terasology/logic/health/HealthComponent.java
> +import org.terasology.network.ClientComponent;
These are unused imports.

2020-03-04 15:18 UTC, e-aakash commented on src/main/java/org/terasology/logic/health/DamageAuthoritySystem.java
> +        highSpeedDamage(speed, entity, height < 30 ? health.horizontalDamageSpeedThreshold : 10000, health.excessSpeedDamageMultiplier);
Should this be hardcoded? maybe this can be moved to some constant in health component.

2020-03-04 15:18 UTC, e-aakash commented on src/main/java/org/terasology/logic/health/HealthComponent.java
> +
Unnecessary newlines added?

2020-04-19 11:10 UTC, skaldarnar requested changes
As stated in this comment https://github.com/MovingBlocks/Terasology/pull/3841#issuecomment-616105139 the health system should react on a scale event, but it should not modify the components `onCrash` or `onLanding`... 

Thus, requesting changes on this PR. I'll create the corresponding event in engine and use it there to adjust values of CharacterComponent and CharacterMovementComponent. You can take that as reference for adjusting the health sytem then 😉

2021-03-20 17:41 UTC, closed without merging